# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QPushButton
import requests
import json
import urllib.request
import pyperclip
from PyQt5.QtGui import QIcon
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowFlags(QtCore.Qt.WindowType.WindowStaysOnTopHint)
        Form.resize(700, 300)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pre = QtWidgets.QTextEdit(Form)
        self.pre.setObjectName("pre")
        self.horizontalLayout_2.addWidget(self.pre)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.textEdit_2 = QtWidgets.QTextEdit(Form)
        self.textEdit_2.setObjectName("textEdit_2")
        self.horizontalLayout_2.addWidget(self.textEdit_2)
        self.pushButton.clicked.connect(self.ts) 
        
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def ts(self):
        t =self.pre.toPlainText()
        srcText = t
        client_id = "j6V6dD6f1YCjncBEOBas"
        client_secret = "9E9BIJvIQ5"
        data = {'text' : srcText,
                'source' : 'ko',
                'target': 'en'}



        url = "https://openapi.naver.com/v1/papago/n2mt"
        header = {"X-Naver-Client-Id":client_id,
                "X-Naver-Client-Secret":client_secret}
        response = requests.post(url, headers=header, data= data)
        rescode = response.status_code
        t_data = response.json()
        try:
            result = t_data['message']['result']['translatedText']
            self.textEdit_2.setText(result)
            pyperclip.copy(result)
        except:
            pass

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate


        Form.setWindowTitle(_translate("Form", "번역기"))
        Form.setWindowIcon(QIcon('web.png'))
        self.pushButton.setText(_translate("Form", "translate"))
        self.pushButton.setShortcut("Ctrl+F")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
